inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - "bin/**/*"
